------------------------------------------
-- -------- POPULATE ALL TABLES ----------
------------------------------------------


-- -------- POPULATE TABLE "MODULE" ----------

INSERT INTO APP.MODULE_2 (OID, MODULEID, MODULENAME) VALUES (1, 'sv1', 'Voters');
INSERT INTO APP.MODULE_2 (OID, MODULEID, MODULENAME) VALUES (2, 'sv3', 'Administrators');



-- -------- POPULATE TABLE "GROUP" ----------

INSERT INTO "APP"."GROUP_2" (OID, GROUPNAME) VALUES (1, 'Voters');
INSERT INTO "APP"."GROUP_2" (OID, GROUPNAME) VALUES (2, 'Administrators');


-- -------- POPULATE TABLE "GROUP_MODULETABLE" ----------

INSERT INTO APP.GROUP_MODULE_2 (GROUP_2_OID, MODULE_2_OID) VALUES (1, 1);
INSERT INTO APP.GROUP_MODULE_2 (GROUP_2_OID, MODULE_2_OID) VALUES (2, 2);

-- -------- POPULATE TABLE "USER" ----------

INSERT INTO "APP"."USER_2" (OID, USERNAME, PASSWORD, EMAIL) VALUES (1, 'user', 'user', 'user@test.com');
INSERT INTO "APP"."USER_2" (OID, USERNAME, PASSWORD, EMAIL) VALUES (2, 'admin', 'admin', 'admin@test.com');

-- -------- POPULATE TABLE "USER_GROUP" ----------

INSERT INTO APP.USER_GROUP_2 (USER_2_OID, GROUP_2_OID) VALUES (1, 1);
INSERT INTO APP.USER_GROUP_2 (USER_2_OID, GROUP_2_OID) VALUES (2, 2);

-- -------- POPULATE TABLE "EXHIBIT" ----------

INSERT INTO APP.EXHIBIT_2 (OID, NAME) VALUES (1, 'Science');
INSERT INTO APP.EXHIBIT_2 (OID, NAME) VALUES (2, 'WebRatio');